package com.example.aws.demo.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Builder
@Getter
@Setter
@DynamoDBTable(tableName = "filemetadata")
public class FileMetadata {
    @DynamoDBHashKey(attributeName = "UserId")
    private String userId;

    @DynamoDBAttribute(attributeName = "FileId")
    private String fileId;

    @DynamoDBAttribute(attributeName = "FileName")
    private String fileName;

    @DynamoDBAttribute(attributeName = "FileSize")
    private Long fileSize;
    @DynamoDBAttribute(attributeName = "CreatedAt")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date createdAt;

    @DynamoDBAttribute(attributeName = "UpdatedAt")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    private Date updatedAt;
}
